### ISSUE TITLE
Copy highlight feature

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CuriousReaderInteractiveFunctionsH5P#156]
When adding a glow effect to multiple objects for the same word, it would be great to be able to save time by copying and pasting a glow effect so one only has to adjust the size of the glow.

**Comment by dz4va** [comment]
They glow object itself can be copied by CMD + C (CTRL + C Win) and pasted by CMD+ V (CTRL + V Win) @burrage

**Comment by burrage** [comment]
George and I found out that on a Mac it is STILL CTRL + C for copying and CTRL + V for pasting (unlike normal Mac conventions... whhyyyyyy!!!)
