### ISSUE TITLE
only allow the user to select an existing words.

### ISSUE THREAD

**Issue by Rajesh1041** [curiouslearning/CuriousReaderInteractiveFunctionsH5P#47]
- When creating timestamps, only allow the user to select an existing word from text appearing on the page
     -- we don’t want them to have to re-type a word or put in a word that doesn’t exist already (in the Unity 
     version, we had people select from a dropdown menu but it doesn’t have to be like that-- maybe checkbox 
     selectors? What would be easiest?)

- Handle edge case where someone tries to add audio when they haven’t put in text first

**Comment by pks99ing** [comment]
while creating time stamp we are able to select the text which we have already entered in the advance text field as a form of checkbox and auto play is also playing absolutely fine.
But if i clone the slide then text in the second slide is not visible.
Same things happens in first slide after saving and the click on edit again.
