### ISSUE TITLE
Text on slide disappears when adding an image or adding a Curious Reader Audio

### ISSUE THREAD

**Issue by Rajesh1041** [curiouslearning/CuriousReaderInteractiveFunctionsH5P#51]
1. Add text
2. Open add image dialogue and rather than adding image and click done, 
do delete image
3. then text also gets deleted

**Comment by burrage** [comment]
To add more to this, the text object actually still persists as you can click where the text was and still see that the text object is there and even resize the space that text object has and where you want it on the slide.

To temporarily get the text back, delete one letter and save. Text reappears. Edit again to add back the letter that was deleted.
