### ISSUE TITLE
Book with Narrative Audio

### ISSUE THREAD

**Issue by Rajesh1041** [curiouslearning/CuriousReaderInteractiveFunctionsH5P#7]
Ability to auto-play a narrative audio file when a new page is navigated to.
Function to create a highlight (yellow text) effect on a single word and un-highlight.
Ability to input timestamps of when a word should highlight in sequence.
Ability to automatically trigger the highlight and size effects based on the timestamps.
Animation function to increase and decrease size of a single OBJECT (e.g. a graphic).

@pks99ing is tester for this task

**Comment by pks99ing** [comment]
1. Able to play play audio but for the first slide it is not playing automatically.
2. Able to highlight audio-text (sync) ,but only for first slide it is working.
3. Able to add time stamp(working fine)
4. Ability to automatically trigger the highlight and size effects based on the timestamps.(implemented and working fine but only for first slide)
5. Animation function to increase and decrease size of a single OBJECT (e.g. a graphic).(yet to be implemented)
