### ISSUE TITLE
Remove "presentation" UI text that overlaps the "Slides" dropdown

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CuriousReaderInteractiveFunctionsH5P#70]
![Screen Shot 2021-09-03 at 1.07.40 PM.png](https://images.zenhubusercontent.com/58c973a851aa2c3057788ef8/562d2bd4-2645-4c7e-96b7-a9ae851b8919)

This looks weird in the UI. Let's remove the word "presentation" because I don't think it's really adding anything to the understanding of the UI anyway.

**Comment by redpixr** [comment]
I have moved the slides dropdown to be floating right in that container, so I guess that's a fix for now
