### ISSUE TITLE
Moving text object forward after adding a Curious Reader Audio object breaks autoplay connection

### ISSUE THREAD

**Issue by burrage** [curiouslearning/CuriousReaderInteractiveFunctionsH5P#74]
**Describe the bug**
When manipulating the text, like using the "Bring to front" option, AFTER you have created a Curious Reader Audio object seems to break autoplay completely with no way to reconnect the two objects.

**To Reproduce**
1. Go to a slide.
2. Add text.
3. Add image.
4. Add audio.
5. Make sure autoplay and everything is working appropriately.
6. Go back and edit the slide and manipulate the text object by using the "Bring to front" feature.

**Expected behavior**
No matter how the text object changes physically, the text should remain linked to the Curious Reader Audio object.

**Screenshots**
Text exists--
![Screen Shot 2021-09-03 at 3.50.26 PM.png](https://images.zenhubusercontent.com/58c973a851aa2c3057788ef8/62291c00-c91c-4c17-ab65-5f023b8545ad)

And timestamps are still there--
![Screen Shot 2021-09-03 at 3.50.37 PM.png](https://images.zenhubusercontent.com/58c973a851aa2c3057788ef8/97104204-398b-4fe4-9f2a-9a08f9ced181)

But no longer connected :~(

**Desktop (please complete the following information):**
OS: Mac
Browser: Chrome
Version: 92.0.4515.159

**Additional context**
N/A

**Comment by Rajesh1041** [comment]
That was the waveform error in console. Once that is fixed it will be gone.
